theme = "tokyonight"

[keys.normal]
C-o = ":config-open"
C-r = ":config-reload"

C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
auto-completion = true
auto-format = true
color-modes = true
default-yank-register = "+"
end-of-line-diagnostics = "disable"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true


[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1



[editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.insert]

C-space = "completion"
